version: "3.9"

services:
  db:
    image: postgres:latest
    env_file:
      - .env.dev
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    
  web:
    build: 
      context: hackernews_clone_vue
      dockerfile: dockerfiles/dev.Dockerfile
    image: yusufertekin/hackernews-scrapper-vue
    command: npm run dev
    volumes:
      - ./hackernews_clone_vue:/web
    ports:
      - "8080:8080"
    depends_on:
      - app

  app:
    build:
      context: hackernews_clone
      dockerfile: dockerfiles/dev.Dockerfile
    image: yusufertekin/hackernews-scrapper
    command: >
      bash -c "python wait_for_it.py db 5432 
      && python manage.py migrate 
      && python manage.py loaddata initial_data 
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./hackernews_clone:/code
    env_file:
      - .env.dev
    depends_on:
      - db

  celery_beat:
    image: yusufertekin/hackernews-scrapper
    command: >
      bash -c "python wait_for_it.py redis 6379 &&
      watchmedo auto-restart --directory=./ --pattern=*.py --recursive --
      celery -A hackernews_clone beat -l INFO
      --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./hackernews_clone:/code
    env_file:
      - .env.dev

  celery_worker_1:
    image: yusufertekin/hackernews-scrapper
    command: > 
      bash -c "python wait_for_it.py redis 6379 &&
      watchmedo auto-restart --directory=./ --pattern=*.py --recursive --
      celery -A hackernews_clone worker -Q main_queue
      --autoscale=6,2 -l INFO"
    volumes:
      - ./hackernews_clone:/code
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  celery_worker_2:
    image: yusufertekin/hackernews-scrapper
    command: > 
      bash -c "python wait_for_it.py redis 6379 &&
      watchmedo auto-restart --directory=./ --pattern=*.py --recursive --
      celery -A hackernews_clone worker
      -Q scrap_page_queue,api_post_queue --autoscale=6,2 -l INFO"
    volumes:
      - ./hackernews_clone:/code
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  celery_worker_3:
    image: yusufertekin/hackernews-scrapper
    command: >
      bash -c "python wait_for_it.py redis 6379 &&
      watchmedo auto-restart --directory=./ --pattern=*.py --recursive --
      celery -A hackernews_clone worker -Q persist_queue --autoscale=6,2 -l INFO" 
    volumes:
      - ./hackernews_clone:/code
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  celery_worker_4:
    image: yusufertekin/hackernews-scrapper
    command: >
      bash -c "python wait_for_it.py redis 6379 &&
      watchmedo auto-restart --directory=./ --pattern=*.py --recursive --
      celery -A hackernews_clone worker -Q sentiment_queue --autoscale=6,2 -l INFO" 
    volumes:
      - ./hackernews_clone:/code
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower
    env_file:
      - .env.dev
    ports:
      - 5555:5555
