# Generated by Django 3.1.4 on 2021-01-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('subject', models.TextField()),
                ('url', models.TextField()),
                ('age', models.CharField(max_length=15)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=15, null=True)),
                ('num_of_comments', models.IntegerField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.TextField()),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['rank'], name='posts_post_rank_fdd6ac_idx'),
        ),
    ]
